# Configuration du réseau Hyperledger Fabric pour le système bancaire UEMOA

# Définition des organisations participantes au réseau
Organizations:

    # Configuration de l'organisation Orderer (service de commande)
    - &OrdererOrg
        Name: OrdererOrg        # Nom de l'organisation Orderer
        ID: OrdererMSP         # Identifiant MSP (Membership Service Provider)
        MSPDir: ../crypto-material/ordererOrganizations/bceao.com/msp  # Chemin vers les certificats MSP
        # Définition des politiques d'accès pour l'Orderer
        Policies:
            Readers:            # Politique de lecture
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:            # Politique d'écriture
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:             # Politique d'administration
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        # Point de terminaison du service Orderer
        OrdererEndpoints:
            - orderer0.bceao.com:7050

    # Configuration de la banque Ecobank
    - &Ecobank
        Name: Ecobank
        ID: EcobankMSP
        MSPDir: ../crypto-material/peerOrganizations/ecobank.bceao.com/msp
        # Politiques spécifiques à Ecobank
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('EcobankMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('EcobankMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('EcobankMSP.admin')"
            Endorsement:        # Politique d'approbation des transactions
                Type: Signature
                Rule: "OR('EcobankMSP.member')"
        # Définition du peer ancre pour Ecobank
        AnchorPeers:
            - Host: peer0.ecobank.bceao.com
              Port: 7051

    # Configuration de la banque Corisbank
    - &Corisbank
        Name: Corisbank
        ID: CorisbankMSP
        MSPDir: ../crypto-material/peerOrganizations/corisbank.bceao.com/msp
        # Politiques spécifiques à Corisbank
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CorisbankMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('CorisbankMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('CorisbankMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('CorisbankMSP.member')"
        # Définition du peer ancre pour Corisbank
        AnchorPeers:
            - Host: peer0.corisbank.bceao.com
              Port: 8051

# Définition des capacités du réseau (fonctionnalités activées)
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true            # Utilisation des fonctionnalités de Fabric v2.0 pour les canaux
    Orderer: &OrdererCapabilities
        V2_0: true            # Fonctionnalités v2.0 pour l'Orderer
    Application: &ApplicationCapabilities
        V2_0: true            # Fonctionnalités v2.0 pour les applications

# Configuration par défaut des applications
Application: &ApplicationDefaults
    Organizations:
    # Politiques par défaut pour les applications
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"      # Tout lecteur peut lire
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"      # Tout écrivain peut écrire
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"  # Majorité des admins requise
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"  # Majorité requise pour le cycle de vie du chaincode
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"  # Majorité requise pour l'approbation
    Capabilities:
        <<: *ApplicationCapabilities

# Configuration par défaut de l'Orderer
Orderer: &OrdererDefaults
    OrdererType: etcdraft      # Type de consensus utilisé
    # Configuration du consensus Raft
    EtcdRaft:
        Consenters:
        - Host: orderer0.bceao.com
          Port: 7050
          ClientTLSCert: ../crypto-material/ordererOrganizations/bceao.com/orderers/orderer0.bceao.com/tls/server.crt
          ServerTLSCert: ../crypto-material/ordererOrganizations/bceao.com/orderers/orderer0.bceao.com/tls/server.crt
    # Configuration du traitement des transactions
    BatchTimeout: 2s           # Temps maximum d'attente avant de créer un bloc
    BatchSize:
        MaxMessageCount: 10    # Nombre maximum de messages par bloc
        AbsoluteMaxBytes: 99 MB    # Taille maximale d'un bloc
        PreferredMaxBytes: 512 KB   # Taille préférée d'un bloc
    Organizations:
    # Politiques de l'Orderer
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

# Configuration par défaut du canal
Channel: &ChannelDefaults
    # Politiques du canal
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

# Profils de configuration du réseau
Profiles:
    # Profil pour la création du bloc de genèse
    ApNetworkProfile:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        # Définition du consortium (groupe d'organisations)
        Consortiums:
            ApConsortium:
                Organizations:
                    - *Ecobank
                    - *Corisbank

    # Profil pour la création du canal
    ApChannelProfile:
        Consortium: ApConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Ecobank
                - *Corisbank
            Capabilities:
                <<: *ApplicationCapabilities