version: '3'

volumes:
  peer0.ecobank.bceao.com:
  peer1.ecobank.bceao.com:

networks:
  bceaonet:

services:

  couchdbeco0:
    container_name: couchdbeco0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - bceaonet

  peer0.ecobank.bceao.com:
    networks:
      - bceaonet   
    container_name: peer0.ecobank.bceao.com
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # Generic peer variables
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Specific peer variables
      - CORE_PEER_ID=peer0.ecobank.bceao.com
      - CORE_PEER_ADDRESS=peer0.ecobank.bceao.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      # chaincode variables
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_CHAINCODEADDRESS=peeer0.ecobank.bceao.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      # GOSSIP configuration
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ecobank.bceao.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ecobank.bceao.com:7042
      - CORE_PEER_LOCALMSPID=EcobankMSP
    volumes:
        - /var/run/:/host/var/run/
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-material/peerOrganizations/ecobank.bceao.com/peers/peer0.ecobank.bceao.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-material/peerOrganizations/ecobank.bceao.com/peers/peer0.ecobank.bceao.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ecobank.bceao.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdbeco0
    ports:
      - 7051:7051
    
  couchdbeco1:
    container_name: couchdbeco1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:6984
    networks:
      - bceaonet

  peer1.ecobank.bceao.com:
    networks:
      - bceaonet   
    container_name: peer1.ecobank.bceao.com
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - GODEBUG=netdns=go
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bceaonet
      # Specific peer variables
      - CORE_PEER_ID=peer1.ecobank.bceao.com
      - CORE_PEER_ADDRESS=peer1.ecobank.bceao.com:7042
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7042
      # chaincode variables
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_CHAINCODEADDRESS=peeer1.ecobank.bceao.com:7043
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7043
      # GOSSIP configuration
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ecobank.bceao.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ecobank.bceao.com:7042
      - CORE_PEER_LOCALMSPID=EcobankMSP
    volumes:
        - /var/run/:/host/var/run/
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-material/peerOrganizations/ecobank.bceao.com/peers/peer1.ecobank.bceao.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-material/peerOrganizations/ecobank.bceao.com/peers/peer1.ecobank.bceao.com/tls:/etc/hyperledger/fabric/tls
        - peer1.ecobank.bceao.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdbeco1
    ports:
      - 7042:7042