version: '3'

volumes:
  peer0.bceaoorg.bceao.com:
  peer1.bceaoorg.bceao.com:

networks:
  bceaonet:

services:

  couchdbbceao0:
    container_name: couchdbbceao0
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 3004:3004
    networks:
      - bceaonet

  peer0.bceaoorg.bceao.com:
    networks:
      - bceaonet   
    container_name: peer0.bceaoorg.bceao.com
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # Generic peer variables
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Specific peer variables
      - CORE_PEER_ID=peer0.bceaoorg.bceao.com
      - CORE_PEER_ADDRESS=peer0.bceaoorg.bceao.com:2024
      - CORE_PEER_LISTENADDRESS=0.0.0.0:2024
      # chaincode variables
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_bceaonet
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${IMAGE_TAG}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${IMAGE_TAG}
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:${IMAGE_TAG}
      - CORE_PEER_CHAINCODEADDRESS=peer0.bceaoorg.bceao.com:2025
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:2025
      # GOSSIP configuration
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bceaoorg.bceao.com:2024
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bceaoorg.bceao.com:3024
      - CORE_PEER_LOCALMSPID=BCEAOORGMSP
      # Ajout pour l'accès à l'API locale
      - CORE_VM_DOCKER_HOSTCONFIG_DNS=8.8.8.8
      - FACE_API_URL=http://172.17.0.1:5021/api/face-recognition
      # Gestion des Timeout.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_GOSSIP_DIALTIMEOUT=300s
      - CORE_PEER_GOSSIP_RESPONSETIMEOUT=300s
      - FABRIC_LOGGING_SPEC=DEBUG
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
        - /var/run/:/host/var/run/
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-material/peerOrganizations/bceaoorg.bceao.com/peers/peer0.bceaoorg.bceao.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-material/peerOrganizations/bceaoorg.bceao.com/peers/peer0.bceaoorg.bceao.com/tls:/etc/hyperledger/fabric/tls
        - ../../chaincode-javascript/assets:/usr/local/src
        - peer0.bceaoorg.bceao.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdbbceao0
    ports:
      - 2024:2024
    
  couchdbbceao1:
    container_name: couchdbbceao1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 4004:4004
    networks:
      - bceaonet

  peer1.bceaoorg.bceao.com:
    networks:
      - bceaonet   
    container_name: peer1.bceaoorg.bceao.com
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    environment:
      # Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # - GODEBUG=netdns=go
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bceaonet
      # Specific peer variables
      - CORE_PEER_ID=peer1.bceaoorg.bceao.com
      - CORE_PEER_ADDRESS=peer1.bceaoorg.bceao.com:3024
      - CORE_PEER_LISTENADDRESS=0.0.0.0:3024
      # chaincode variables
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_bceaonet
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${IMAGE_TAG}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${IMAGE_TAG}
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:${IMAGE_TAG}
      - CORE_PEER_CHAINCODEADDRESS=peer1.bceaoorg.bceao.com:3025
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:3025
      # GOSSIP configuration
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bceaoorg.bceao.com:2024
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bceaoorg.bceao.com:3024
      - CORE_PEER_LOCALMSPID=BCEAOORGMSP
      # Ajout pour l'accès à l'API locale
      - CORE_VM_DOCKER_HOSTCONFIG_DNS=8.8.8.8
      - FACE_API_URL=http://172.17.0.1:5021/api/face-recognition
      # Gestion des Timeout.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_GOSSIP_DIALTIMEOUT=300s
      - CORE_PEER_GOSSIP_RESPONSETIMEOUT=300s
      - FABRIC_LOGGING_SPEC=DEBUG
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
        - /var/run/:/host/var/run/
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../crypto-material/peerOrganizations/bceaoorg.bceao.com/peers/peer1.bceaoorg.bceao.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-material/peerOrganizations/bceaoorg.bceao.com/peers/peer1.bceaoorg.bceao.com/tls:/etc/hyperledger/fabric/tls
        - ../../chaincode-javascript/assets:/usr/local/src
        - peer1.bceaoorg.bceao.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdbbceao1
    ports:
      - 3024:3024